### ISSUE TITLE
Question: How is this different from pop-global-mark ?

### ISSUE THREAD

**Issue by noorul** [ska2342/detour#1]

**Comment by Knusper** [comment]
For reference: http://ergoemacs.org/emacs/emacs_jump_to_previous_position.html

**Comment by ska2342** [comment]
`pop-global-mark` works with the normal mark stack and allows you to jump to a position once. With detour, you explicitly save a mark where you're currently working, go somewhere else and then toggle between those two locations. No stack and the mark is not lost because it is stored inside a register.

I'm aware that this is a very tiny library. But I've been using this for close to 20 years now and it is one of those tiny gems that make Emacs better for me. Thought others might find it useful, too.

**Comment by ska2342** [comment]
@noorul did I answer your question so that this issue can be closed?

**Comment by zeltak** [comment]
I love it thx!

Z

**Comment by noorul** [comment]
@ska2342  Thank you for the explanation.
